<?php
namespace KPI\DBlock;

class PerDayCreditSales extends DBlockPerDay{


    function __construct(array $filters=null, $limit=null) {
        parent::__construct($filters,$limit);

        $whereFilters = "";
        if($this->filters) {
            $whereFilters = "";
            foreach($this->filters as $key=>$value) {
                $whereFilters .= "AND $key = '$value' ";
            }
        }

        $this->qu1 = "
        
        SELECT dt.id, SUM(fp.total_revenue)
        FROM fact_payments AS fp 
        LEFT JOIN dimension_payment_method AS dpm ON dpm.id = fp.dimension_payment_method_id
        LEFT JOIN dimension_time AS dt ON dt.id = fp.dimension_time_id
        INNER JOIN dimension_location AS dl ON dl.id = fp.dimension_location_id
        WHERE dpm.id = 211 AND dt.id >= ".self::$startDate." AND dt.id <= ".self::$endDate." ".
            $whereFilters.
        "GROUP BY dt.id
        ORDER BY dt.id DESC"

        ;

        $this->setName("€ Credits(Payline)[[Credit Revenue - Revenue generated by credit purchases]]");
        
    }

}

?>